/* Core / peripheral interrupt handlers.
 *
 * If your Keil project was generated by CubeMX it already ships with its own
 * stm32f4xx_it.c - in that case DELETE this file and instead:
 *   1) Call HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_0) inside the existing
 *      EXTI0_IRQHandler in the CubeMX-generated file.
 *   2) The SysTick/fault handlers are already provided there.
 *
 * Otherwise (bare Keil project, no CubeMX) include this file and you're done.
 */

#include "stm32f4xx_hal.h"
#include "debug.h"

void SysTick_Handler(void)  { HAL_IncTick(); }

void NMI_Handler(void)       { while (1); }
void HardFault_Handler(void) { DBGE("HardFault!"); while (1); }
void MemManage_Handler(void) { while (1); }
void BusFault_Handler(void)  { while (1); }
void UsageFault_Handler(void){ while (1); }
void SVC_Handler(void)       { }
void DebugMon_Handler(void)  { }
void PendSV_Handler(void)    { }

/* Tamper button - PA0 */
void EXTI0_IRQHandler(void) { HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_0); }
